### ISSUE TITLE
Stickers cause errors

### ISSUE THREAD

**Issue by kantaiz3** [silveredgold/beta-censoring#9]
I'm using beta censoring in combination with beta protection and I noticed that using stickers causes images to error. So only the error image gets displayed. When I switch from stickers to another censoring method, those images are processed correctly.

Luckily, there is a stack trace. While the server itself does not log a trace (I couldn't fine one), the browser extension does :)

```
BP - Error response from censoring request! Error encountered while censoring this image: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index')
   at System.Linq.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument )
   at System.Linq.Enumerable.ElementAt[TSource](IEnumerable`1 , Int32 )
   at BetaCensor.Web.StickerDbProvider.GetRandomImage(String imageType, Nullable`1 ratio, List`1 category) in /home/runner/work/beta-censoring/beta-censoring/src/BetaCensor.Web/StickerDbProvider.cs:line 45
   at CensorCore.Censoring.StickerProvider.GetImageAsync(Nullable`1 boxRatio, List`1 categories) in /home/runner/work/censor-core/censor-core/src/CensorCore/Censoring/StickerProvider.cs:line 78
   at CensorCore.Censoring.StickerProvider.CensorImage(Image`1 inputImage, Classification result, String method, Int32 level) in /home/runner/work/censor-core/censor-core/src/CensorCore/Censoring/StickerProvider.cs:line 37
   at CensorCore.Censoring.ImageSharpCensoringProvider.CensorImage(ImageResult image, IResultParser parser) in /home/runner/work/censor-core/censor-core/src/CensorCore/Censoring/ImageSharpCensoringProvider.cs:line 72
   at BetaCensor.Core.Messaging.CensorImageRequestHandler.Handle(CensorImageRequest request, CancellationToken cancellationToken) in /home/runner/work/beta-censoring/beta-censoring/src/BetaCensor.Core/Messaging/CensorImageRequestHandler.cs:line 54 (Specified argument was out of the range of valid values. (Parameter 'index')) cb0b5c3d-aa07-4b95-8d81-be5039778d61
```

My guess is that the `.Random()` in `GetRandomImage` doesn't work on empty collections. So there probably has to be some exception for when there are no matching stickers.

**Comment by silveredgold** [comment]
Well, yeah, if you ask for stickers but don't give the servers any stickers, then it's going to error out. If you want to use stickers for censoring, your chosen backend needs to have stickers available.

**Comment by kantaiz3** [comment]
I do have stickers loaded, but they "only" work most of the time. Sometimes I get this error.
